spring.application.name=divulgai
server.port=8080

# URL de conexo para o banco de dados no Somee
spring.datasource.url=jdbc:sqlserver://divulgaibanco.mssql.somee.com:1433;databaseName=divulgaibanco;encrypt=false;trustServerCertificate=true

# Credenciais de acesso ao banco no Somee
spring.datasource.username=divulgaisomee
spring.datasource.password=grupo2sql

# Driver do SQL Server
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuraes do JPA e Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false


# spring.application.name=divulgai
# server.port=8080
#
## Conexo correta com Somee
#spring.datasource.url=jdbc:sqlserver://bd_divulgai.mssql.somee.com:1433;databaseName=bd_divulgai;encrypt=true;trustServerCertificate=true
#spring.datasource.username=divulgai
#spring.datasource.password=12345678
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
## JPA
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.open-in-view=false
#
# spring.datasource.url=jdbc:sqlserver://localhost:1433;bd_divulgai.mssql.somee.com;encrypt=false;trustServerCertificate=true
# spring.datasource.username=divulgai
# spring.datasource.password=12345678


# Informaes:

    # integratedSecurity: (true) Indica que a conexo ser feita com as credenciais do Windows (false) Credencial so SQL SERVER
    # encrypt: (true) Requer criptografia do Cliente (false) No requer criptografia do Cliente
    # trustServerCertificate: (true)Instrui o aplicativo cliente a ignorar a validao do certificado SSL/TSL do servidor
    # spring.jpa.hibernate.ddl-auto: (none) Banco de dados e tabelas devem ser criadas com antecedncia
    #                                (update) Banco de dados deve ser criado com antecedncia, o cdigo cria as tabelas e a atualiza quando h alterao no cdigo
    #                                atualiza quando h alterao no cdigo
    #                                (create-drop) Banco de dados deve ser criado com antecedncia, o cdigo cria as tabelas
    #                                entretanto quando o servidor  desligado, as tabelas sero excludas
    #                                (create) Banco degit dados deve ser criado com antecedncia, quando o servidor carrega as
    #                                informaes so excludas
